OJS.Web/Areas/Contests/ViewModels/Tests/TestInputDataViewModel.cs
namespace OJS.Web.Areas.Contests.ViewModels.Tests
{
    public class TestInputDataViewModel
    {
        public int TestId { get; set; }

        public string InputData { get; set; }
    }
}

OJS.Web/Areas/Administration/Controllers/TestsController.cs
namespace OJS.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net.Mime;
    using System.Text;
    using System.Transactions;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Mvc.Expressions;

    using Ionic.Zip;

    using Kendo.Mvc.UI;

    using OJS.Common;
    using OJS.Common.Extensions;
    using OJS.Common.Helpers;
    using OJS.Data;
    using OJS.Data.Models;
    using OJS.Services.Business.Problems;
    using OJS.Services.Business.Submissions;
    using OJS.Services.Data.Problems;
    using OJS.Services.Data.Submissions;
    using OJS.Services.Data.TestRuns;
    using OJS.Services.Data.Tests;
    using OJS.Web.Areas.Administration.Controllers.Common;
    using OJS.Web.Areas.Administration.ViewModels.Problem;
    using OJS.Web.Areas.Administration.ViewModels.Test;
    using OJS.Web.Areas.Administration.ViewModels.TestRun;
    using OJS.Web.Common;
    using OJS.Web.Common.Extensions;
    using OJS.Web.Common.ZippedTestManipulator;
    using OJS.Workers.Common;

    using static OJS.Web.Common.WebConstants;

    using GeneralResource = Resources.Areas.Administration.AdministrationGeneral;
    using Resource = Resources.Areas.Administration.Tests.TestsControllers;

    /// <summary>
    /// Controller class for administrating problems' input and output tests, inherits Administration controller for authorisation
    /// </summary>
    public class TestsController : LecturerBaseController
    {
        private readonly IProblemsDataService problemsData;
        private readonly ISubmissionsDataService submissionsData;
        private readonly ITestRunsDataService testRunsData;
        private readonly ITestsDataService testsData;
        private readonly IProblemsBusinessService problemsBusiness;
        private readonly ISubmissionsBusinessService submissionsBusiness;

        /// <summary>
        /// Initializes a new instance of the <see cref="TestsController"/> class.
        /// </summary>
        public TestsController(
            IOjsData data,
            IProblemsDataService problemsData,
            ISubmissionsDataService submissionsData,
            ITestRunsDataService testRunsData,
            ITestsDataService testsData,
            IProblemsBusinessService problemsBusiness,
            ISubmissionsBusinessService submissionsBusiness)
            : base(data)
        {
            this.problemsData = problemsData;
            this.submissionsData = submissionsData;
            this.testRunsData = testRunsData;
            this.testsData = testsData;
            this.problemsBusiness = problemsBusiness;
            this.submissionsBusiness = submissionsBusiness;
        }

        /// <summary>
        /// Returns view for the tests administration index page
        /// </summary>
        /// <returns>View for /Administration/Tests/</returns>
        public ActionResult Index() => this.View();

        /// <summary>
        /// Returns view for the tests administration index page and populates problem, contest, category dropdowns and tests grid if problem id is correct
        /// </summary>
        /// <param name="id">Problem id which tests are populated</param>
        /// <returns>View for /Administration/Tests/Problem/{id}</returns>
        public ActionResult Problem(int? id)
        {
            if (id == null || !this.CheckIfUserHasProblemPermissions(id.Value))
            {
                return this.RedirectToContestsAdminPanelWithNoPrivilegesMessage();
            }

            this.ViewBag.ProblemId = id;

            return this.View(GlobalConstants.Index);
        }

        /// <summary>
        /// Returns view for the tests administration create page with HTTP Get request - creating tests for a problem selected by id
        /// </summary>
        /// <param name="id">Problem id for which a test will be created</param>
        /// <returns>View for /Administration/Tests/Create/ if problem id is correct otherwise redirects to /Administration/Tests/ with proper error message</returns>
        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                this.TempData.AddDangerMessage(Resource.Invalid_problem);
                return this.RedirectToAction(c => c.Index());
            }

            if (!this.CheckIfUserHasProblemPermissions(id.Value))
            {
                return this.RedirectToContestsAdminPanelWithNoPrivilegesMessage();
            }

            var problem = this.problemsData.GetById(id.Value);

            if (problem == null)
            {
                this.TempData.AddDangerMessage(Resource.Invalid_problem);
                return this.RedirectToAction(c => c.Index());
            }

            var test = new TestViewModel
            {
                ProblemId = problem.Id,
                ProblemName = problem.Name,
                OrderBy = this.testsData
                    .GetAllNonTrialByProblem(problem.Id)
                    .OrderByDescending(t => t.OrderBy)
                    .Select(t => t.OrderBy)
                    .FirstOrDefault() + 1
            };

            ImportAllTypesInTest(test);
            return this.View(test);
        }

        /// <summary>
        /// Redirects to Problem action after successful creation of new test with HTTP Post request
        /// </summary>
        /// <param name="id">Problem id for which the posted test will be saved</param>
        /// <param name="test">Created test posted information</param>
        /// <returns>Redirects to /Administration/Tests/Problem/{id} after succesful creation otherwise to /Administration/Test/ with proper error message</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, TestViewModel test)
        {
            if (test == null || !this.ModelState.IsValid)
            {
                ImportAllTypesInTest(test);
                return this.View(test);
            }

            if (!this.problemsData.ExistsById(id))
            {
                this.TempData.AddDangerMessage(Resource.Invalid_problem);
                return this.RedirectToAction(c => c.Index());
            }

            if (!this.CheckIfUserHasProblemPermissions(id))
            {
                return this.RedirectToContestsAdminPanelWithNoPrivilegesMessage();
            }

            this.testsData.Add(new Test
            {
                InputDataAsString = test.InputFull,
                OutputDataAsString = test.OutputFull,
                ProblemId = id,
                IsTrialTest = test.Type == TestType.Trial,
                OrderBy = test.OrderBy,
                IsOpenTest = test.Type == TestType.Open,
                HideInput = test.HideInput,
            });

            if (test.RetestProblem)
            {
                this.problemsBusiness.RetestById(id);
            }

            this.TempData.AddInfoMessage(Resource.Test_added_successfully);
            return this.RedirectToAction(c => c.Problem(id));
        }

        /// <summary>
        /// Returns view for the tests administration edit page with HTTP Get request - editing test by id
        /// </summary>
        /// <param name="id">Id for test to be edited</param>
        /// <returns>View for /Administration/Tests/Edit/{id} otherwise redirects to /Administration/Test/ with proper error message</returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var test = this.testsData
                .GetByIdQuery(id)
                .Select(TestViewModel.FromTest)
                .FirstOrDefault();

            if (test == null)
            {
                this.TempData.AddDangerMessage(Resource.Invalid_test);
                return this.RedirectToAction(c => c.Index());
            }

            if (!this.CheckIfUserHasProblemPermissions(test.ProblemId))
            {
                return this.RedirectToContestsAdminPanelWithNoPrivilegesMessage();
            }

            ImportAllTypesInTest(test);

            return this.View(test);
        }

        /// <summary>
        /// Redirects to Problem action after successful edit of the test with HTTP Post request
        /// </summary>
        /// <param name="id">Id for edited test</param>
        /// <param name="test">Edited test posted information</param>
        /// <param name="retestTask">Value indicating if the problem should be retested</param>
        /// <returns>Redirects to /Administration/Tests/Problem/{id} after succesful edit otherwise to /Administration/Test/ with proper error message</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TestViewModel test)
        {
            if (test == null || !this.ModelState.IsValid)
            {
                ImportAllTypesInTest(test);
                return this.View(test);
            }

            var existingTest = this.testsData.GetById(id);

            if (existingTest == null)
            {
                this.TempData.AddDangerMessage(Resource.Invalid_test);
                return this.RedirectToAction(c => c.Problem(id));
            }

            if (!this.CheckIfUserHasProblemPermissions(existingTest.ProblemId))
            {
                this.RedirectToContestsAdminPanelWithNoPrivilegesMessage();
            }

            using (var scope = TransactionsHelper.CreateTransactionScope(IsolationLevel.RepeatableRead))
            {
                existingTest.InputData = test.InputData;
                existingTest.OutputData = test.OutputData;
                existingTest.OrderBy = test.OrderBy;
                existingTest.IsTrialTest = test.Type == TestType.Trial;
                existingTest.IsOpenTest = test.Type == TestType.Open;

OJS.Web/Areas/Contests/Controllers/TestsController.cs
namespace OJS.Web.Areas.Contests.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;

    using OJS.Data;
    using OJS.Services.Data.Participants;
    using OJS.Services.Data.Submissions;
    using OJS.Services.Data.Tests;
    using OJS.Web.Areas.Contests.ViewModels.Tests;
    using OJS.Web.Controllers;
    using OJS.Workers.Common.Extensions;

    using Resource = Resources.Areas.Contests.Controllers.Tests;

    [Authorize]
    public class TestsController : BaseController
    {
        private readonly ITestsDataService testsData;
        private readonly IParticipantsDataService participantsData;
        private readonly ISubmissionsDataService submissionsData;

        public TestsController(
            IOjsData data,
            ITestsDataService testsData,
            IParticipantsDataService participantsData,
            ISubmissionsDataService submissionsData)
            : base(data)
        {
            this.testsData = testsData;
            this.participantsData = participantsData;
            this.submissionsData = submissionsData;
        }

        [HttpGet]
        public ActionResult GetInputData(int testId, int submissionId)
        {
            var testInfo = this.testsData
                .GetByIdQuery(testId)
                .Select(t => new
                {
                    InputDataAsBytes = t.InputData,
                    t.IsTrialTest,
                    t.IsOpenTest,
                    t.ProblemId,
                    t.Problem.ProblemGroup.ContestId,
                    t.Problem.ShowDetailedFeedback,
                    t.Problem.ProblemGroup.Contest.AutoChangeTestsFeedbackVisibility
                })
                .FirstOrDefault();

            if (testInfo == null)
            {
                throw new HttpException((int)HttpStatusCode.NotFound, Resource.Test_not_found_message);
            }

            if (!ShouldDisplayDetailedTestInfo())
            {
                throw new HttpException((int)HttpStatusCode.Forbidden, Resource.No_rights_message);
            }

            var inputDataViewModel = new TestInputDataViewModel
            {
                InputData = testInfo.InputDataAsBytes.Decompress(),
                TestId = testId
            };

            return this.PartialView("_GetInputDataPartial", inputDataViewModel);

            bool ShouldDisplayDetailedTestInfo()
            {
                var userHasProblemPermissions = this.CheckIfUserHasProblemPermissions(testInfo.ProblemId);

                var userIsParticipant = this.participantsData
                    .ExistsByContestAndUser(testInfo.ContestId, this.UserProfile.Id);

                var userHasTestPermissions = userIsParticipant &&
                    (testInfo.IsTrialTest || testInfo.ShowDetailedFeedback || testInfo.IsOpenTest);

                var isUnofficialSubmission = !this.submissionsData.IsOfficialById(submissionId);

                var testIsOpenForEveryone = testInfo.AutoChangeTestsFeedbackVisibility && isUnofficialSubmission;

                return userHasProblemPermissions || userHasTestPermissions || testIsOpenForEveryone;
            }
        }
    }
}

OJS.Web/Areas/Administration/Views/Tests/Create.cshtml
@using OJS.Web.Areas.Administration.Controllers

@using Resource = Resources.Areas.Administration.Tests.Views.TestsCreate

@model OJS.Web.Areas.Administration.ViewModels.Test.TestViewModel

@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@ViewBag.Title</h2>
<h3>@Model.ProblemName</h3>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.ProblemId)
        @Html.HiddenFor(m => m.ProblemName)

        <div class="editor-label">
            @Html.LabelFor(m => m.InputFull)
        </div>
        <div class="editor-field row">
            @Html.TextAreaFor(m => m.InputFull, new { rows = 10, @class = "col-md-12 form-control monospace-font" })
            @Html.ValidationMessageFor(m => m.InputFull)
        </div>
        <br />
        <div class="editor-label">
            @Html.LabelFor(m => m.OutputFull)
        </div>
        <div class="editor-field row">
            @Html.TextAreaFor(m => m.OutputFull, new { rows = 10, @class = "col-md-12 form-control monospace-font" })
            @Html.ValidationMessageFor(m => m.OutputFull)
        </div>
        <br />
        <div class="row">
            <div class="editor-label">
                @Html.LabelFor(m => m.Type)
            </div>
            <div class="editor-field">
                @Html.Kendo().DropDownListFor(m => m.Type).BindTo(Model.AllTypes).HtmlAttributes(new {style = "width: 22em;"})
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.OrderBy)
            </div>
            <div class="editor-label">
                @Html.EditorFor(m => m.OrderBy)
                @Html.ValidationMessageFor(m => m.OrderBy)
            </div>
            <div class="top-buffer-lg">
                @Html.CheckBoxFor(m => m.RetestProblem)
                @Html.LabelFor(m => m.RetestProblem)
            </div>
            <div class="top-buffer-lg">
                @Html.CheckBoxFor(m => m.HideInput)
                @Html.LabelFor(m => m.HideInput)
            </div>
            <br />
            <button type="submit" class="btn btn-primary">@Resource.Create</button>
            <a href="@(Url.Action<TestsController>(c => c.Problem(Model.ProblemId)))" class="btn btn-primary">@Resource.Back</a>
        </div>
    }
</div>

OJS.Web/Areas/Administration/Views/Tests/Delete.cshtml
@using OJS.Web.Areas.Administration.Controllers

@using Resource = Resources.Areas.Administration.Tests.Views.TestsDelete

@model OJS.Web.Areas.Administration.ViewModels.Test.TestViewModel

@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@ViewBag.Title</h2>
<div class="container">
    @using (Html.BeginForm<TestsController>(c => c.ConfirmDelete(Model.Id), FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="editor-label">
            @Html.LabelFor(m => m.Input)
        </div>
        <div class="panel-body bordered-content editor-field">
            <pre class="monospace-font">@(Model.InputFull.Length > 200 ? Model.InputFull.Substring(0, 200) + "..." : Model.InputFull)</pre>
        </div>
        <br />
        <div class="editor-label">
            @Html.LabelFor(m => m.Output)
        </div>
        <div class="panel-body bordered-content editor-field">
            <pre class="monospace-font">@(Model.OutputFull.Length > 200 ? Model.OutputFull.Substring(0, 200) + "..." : Model.OutputFull)</pre>
        </div>
        <br />
        <div class="editor-label">
            <strong class="text-white">@Model.TrialTestName @Resource.Test</strong>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">@Resource.Delete</button>
        <a href="@(Url.Action<TestsController>(c => c.Problem(Model.ProblemId)))" class="btn btn-primary">@Resource.Back</a>
    }
</div>

OJS.Web/Areas/Administration/Views/Tests/DeleteAll.cshtml
@using Resource = Resources.Areas.Administration.Tests.Views.TestsDeleteAll;
@model OJS.Web.Areas.Administration.ViewModels.Problem.ProblemViewModel

@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@Model.Name</h2>
<h3>@ViewBag.Title</h3>

<p>
    @Resource.Delete_confirmation @Model.Name?
</p>
<a href="/Administration/Tests/ConfirmDeleteAll/@Model.Id" class="btn btn-primary">@Resource.Confirm</a>
<a href="/Administration/Tests/Problem/@Model.Id" class="btn btn-primary">@Resource.Back</a>

OJS.Web/Areas/Administration/Views/Tests/Details.cshtml
@using OJS.Common.Extensions
@using Resource = Resources.Areas.Administration.Tests.Views.TestsDetails;
@model OJS.Web.Areas.Administration.ViewModels.Test.TestViewModel

@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@ViewBag.Title</h2>
<div class="container">
    <div class="editor-label">
        @Html.LabelFor(m => m.ProblemName)
    </div>
    <div class="panel-body bordered-content editor-label">
        @Model.ProblemName
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.Input)
    </div>
    <div class="panel-body bordered-content editor-label">
        <pre id="test-input" class="monospace-font">@(Model.InputFull.Length > 200 ? Model.InputFull.Substring(0, 200) + "..." : Model.InputFull)</pre>

        @if (Model.InputFull.Length > 200)
        {
            @Ajax.ActionLink(Resource.See_more, "FullInput", new { id = @Model.Id }, new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "test-input", InsertionMode = InsertionMode.Replace, OnComplete = "removeInputAjaxLink" }, new { id = "ajax-input-link" })
        }
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.Output)
    </div>
    <div class="panel-body bordered-content editor-label">
        <pre id ="test-output" class="monospace-font">@(Model.OutputFull.Length > 200 ? Model.OutputFull.Substring(0, 200) + "..." : Model.OutputFull)</pre>
        
        @if (Model.OutputFull.Length > 200)
        {
            @Ajax.ActionLink(Resource.See_more, "FullOutput", new { id = @Model.Id }, new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "test-output", InsertionMode = InsertionMode.Replace, OnComplete = "removeOutputAjaxLink" }, new { id = "ajax-output-link" })
        }
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.Type)
    </div>
    <div class="panel-body bordered-content editor-label">
        @Model.Type.GetLocalizedDescription()
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.OrderBy)
    </div>
    <div class="panel-body bordered-content editor-label">
        @Model.OrderBy
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.HideInput)
    </div>
    <div class="panel-body bordered-content editor-label">
        @Model.HideInput
    </div>
    <br />
    <div id="test-runs-grid">

    </div>
    @Ajax.ActionLink(Resource.Show_executions, "GetTestRuns", new { id = Model.Id }, new AjaxOptions { HttpMethod = "Get", OnComplete = "initilizeTestRuns" }, new { id = "test-runs-button", @class = "btn btn-primary" })
    <br />    
    <br />  
    <a href="/Administration/Tests/Edit/@Model.Id" class="btn btn-primary">@Resource.Edit</a>
    <a href="/Administration/Tests/Problem/@Model.ProblemId" class="btn btn-primary">@Resource.Back</a>
</div>

@section scripts {
    <script src="~/Scripts/Administration/Tests/tests-details.js"></script>    
}

OJS.Web/Areas/Administration/Views/Tests/Edit.cshtml
@using OJS.Web.Areas.Administration.Controllers

@using Resource = Resources.Areas.Administration.Tests.Views.TestsEdit

@model OJS.Web.Areas.Administration.ViewModels.Test.TestViewModel

@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@ViewBag.Title</h2>
<h3>@Model.ProblemName</h3>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.ProblemId)
        @Html.HiddenFor(m => m.ProblemName)

        <div class="editor-label">
            @Html.LabelFor(m => m.InputFull)
        </div>
        <div class="editor-field row">
            @Html.TextAreaFor(m => m.InputFull, new { rows = 10, @class = "col-md-12 form-control monospace-font" })
            @Html.ValidationMessageFor(m => m.InputFull)
        </div>
        <br />
        <div class="editor-label">
            @Html.LabelFor(m => m.OutputFull)
        </div>
        <div class="editor-field row">
            @Html.TextAreaFor(m => m.OutputFull, new { rows = 10, @class = "col-md-12 form-control monospace-font" })
            @Html.ValidationMessageFor(m => m.OutputFull)
        </div>
        <br />
        <div class="row">
            <div class="editor-label">
                @Html.LabelFor(m => m.Type)
            </div>
            <div class="editor-field">
                @Html.Kendo().DropDownListFor(m => m.Type).BindTo(Model.AllTypes).HtmlAttributes(new { style = "width: 22em;" })
            </div>
            <div class="editor-label">
                @Html.LabelFor(m => m.OrderBy)
            </div>
            <div class="editor-label">
                @Html.EditorFor(m => m.OrderBy)
                @Html.ValidationMessageFor(m => m.OrderBy)
            </div>
            <div class="top-buffer-lg">
                @Html.CheckBoxFor(m => m.RetestProblem)
                @Html.LabelFor(m => m.RetestProblem)
            </div>
            <div class="top-buffer-lg">
                @Html.CheckBoxFor(m => m.HideInput)
                @Html.LabelFor(m => m.HideInput)
            </div>
            <br />
            <button type="submit" class="btn btn-primary">@Resource.Edit</button>
            <a href="@(Url.Action<TestsController>(c => c.Problem(Model.ProblemId)))" class="btn btn-primary">@Resource.Back</a>
        </div>
    }
</div>

OJS.Web/Areas/Administration/Views/Tests/Index.cshtml
@using Resource = Resources.Areas.Administration.Tests.Views.TestsIndex;
@{
    ViewBag.Title = Resource.Page_title;
}

<h2>@ViewBag.Title</h2>
<div class="container">
    <div class="col-md-6">
        <div>
            <label for="search">@Resource.Search_by_problem </label>
        </div>
        <div>
            @(@Html.Kendo().AutoComplete()
                .Name("search")
                .Placeholder(Resource.Enter_problem)
                .HtmlAttributes(new { @class = "test-file-dropdown" })
                .DataTextField("Name")
                .MinLength(3)
                .DataSource(source =>
                {
                    source
                        .Read(read =>
                        {
                            read.Action("GetProblemsContaining", "KendoRemoteData")
                                .Data("onAdditionalData");
                        })
                        .ServerFiltering(true);
                }
                )
                .Events(e => 
                {
                    e.Select("onSearchSelect").Open("Ojs.KendoControls.DropDownList.alignDropDownToInput");
                }))
        </div>
    </div>
</div>
<div class="container">
    <div class="col-md-6">

        <div>
            <div>
                <label for="categories">@Resource.Category_label </label>
            </div>
            <div>
                @(Html.Kendo().DropDownList()
                    .Name("categories")
                    .OptionLabel(Resource.Choose_category)
                    .HtmlAttributes(new { @class = "test-file-dropdown" })
                    .DataTextField("Name")
                    .DataValueField("Id")
                    .Events(e => e.Open("Ojs.KendoControls.DropDownList.alignDropDownToInput"))
                    .DataSource(source =>
                    {
                        source.Read(read =>
                        {
                            read.Action("GetAvailableCategories", "LecturersKendoRemoteData");
                        });
                    }))
            </div>
        </div>
        <div>
            <label for="contests">@Resource.Contest_label </label>
        </div>
        <div>
            @(Html.Kendo().DropDownList()
                .Name("contests")
                .OptionLabel(Resource.Choose_contest)
                .HtmlAttributes(new { @class = "test-file-dropdown" })
                .DataTextField("Name")
                .DataValueField("Id")
                .Events(e => e.Open("Ojs.KendoControls.DropDownList.alignDropDownToInput"))
                .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetCascadeContestsFromCategory", "LecturersKendoRemoteData")
                            .Data("filterContests");
                    })
                    .ServerFiltering(true);
                })
                .Enable(false)
                .AutoBind(false)
                .CascadeFrom("categories")
            )
        </div>
        <div>
            <label for="problems">@Resource.Problem_label </label>
        </div>
        <div>
            @(Html.Kendo().DropDownList()
                .Name("problems")
                .OptionLabel(Resource.Choose_problem)
                .HtmlAttributes(new { @class = "test-file-dropdown" })
                .DataTextField("Name")
                .DataValueField("Id")
                .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetCascadeProblemsFromContest", "KendoRemoteData")
                            .Data("filterProblems");
                    })
                    .ServerFiltering(true);
                })
                .Enable(false)
                .AutoBind(false)
                .CascadeFrom("contests")
                .Events(e => e.Change("onProblemSelect").Open("Ojs.KendoControls.DropDownList.alignDropDownToInput"))
            )
        </div>
    </div>
    <div id="controls">
        @using (Html.BeginForm("Import", "Tests", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            
            <div class="col-md-6 pull-right">
                <div class="col-md-7 pull-right">
                    @if (ViewBag.ProblemId != null)
                    {
                        <input id="problemId" name="problemId" type="text" value="@ViewBag.ProblemId" />
                    }
                    else
                    {
                        <input id="problemId" name="problemId" type="text" />
                    }
                    <div>
                        @Html.CheckBox("retestTask", false)
                        @Html.Label(Resource.Retest_problem, new { @for = "retestTask", style = "display: inline-block; " })
                    </div>
                    <div>
                        @Html.CheckBox("deleteOldFiles", true)
                        @Html.Label(Resource.Delete_old_tests, new { @for = "deleteOldFiles", style = "display: inline-block; " })
                    </div>
                    <p>
                        @Html.Kendo().Upload().Name("file").Multiple(false).HtmlAttributes(new { @class = "kendo-upload" })
                        <input class="k-button" type="submit" value="@Resource.Import" />
                    </p>
                </div>
            </div>
        }
    </div>
</div>
<br />
<div class="jumbotron text-center text-white" id="status">@Resource.Tests_loading</div>
<div id="grid"></div>

@section scripts{
    <script src="~/Scripts/Administration/Tests/tests-index.js"></script>
}